services:
  db:
    image: mysql:latest
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: Prueba+1234
      MYSQL_PASSWORD: Prueba+1234
      MYSQL_DATABASE: pets
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - '3306:3306'
  
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
     - "8082:80"
    environment:
      MYSQL_ROOT_PASSWORD: Prueba+1234
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: Prueba+1234

  myapp:
    container_name: myapp
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    ports:
      - 3000:3000

volumes:
  my-db:

